#ifndef __MQTT_SERVER_SETTING_H__
#define __MQTT_SERVER_SETTING_H__

#define IOTHUB_AUTH_CLIENT_SIDE_CERT    1
#define IOTHUB_AUTH_SYMMETRIC_KEY       2

// Set your authentication method here
//Azure
#define IOTHUB_AUTH_METHOD              IOTHUB_AUTH_CLIENT_SIDE_CERT

//Azure
#define DEVICE_ID                       "STM32IOT"
#define MQTT_SERVER_HOST_NAME           "HomeBase.azure-devices.net"
#define MQTT_SERVER_PASSWORD            "ignored"   // If you're using symmetric key authentication, set this to an SAS Token



#define MQTT_SERVER_PORT                8883




/*
 * Root CA certificate here in PEM format.
 * "-----BEGIN CERTIFICATE-----\n"
 * ...
 * "-----END CERTIFICATE-----\n";
 */
// Obtained from https://os.mbed.com/users/AzureIoTClient/code/simplesample_mqtt/file/c48c89945a83/certs.c/
const char* SSL_CA_PEM =
/* Baltimore */
"-----BEGIN CERTIFICATE-----\r\n"
"MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ\r\n"
"RTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD\r\n"
"VQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX\r\n"
"DTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y\r\n"
"ZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVy\r\n"
"VHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKr\r\n"
"mD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjr\r\n"
"IZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeK\r\n"
"mpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSu\r\n"
"XmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZy\r\n"
"dc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM71oGDHweI12v/ye\r\n"
"jl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1\r\n"
"BE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3\r\n"
"DQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT92\r\n"
"9hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3Wgx\r\n"
"jkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0\r\n"
"Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhz\r\n"
"ksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRCwBXbsdtTLS\r\n"
"R9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp\r\n"
"-----END CERTIFICATE-----\r\n"
/* Microsoft IT */
"-----BEGIN CERTIFICATE-----\r\n"
"MIIFtDCCBJygAwIBAgIQDywQyVsGwJN/uNRJ+D6FaTANBgkqhkiG9w0BAQsFADBa\r\n"
"MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl\r\n"
"clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTE2\r\n"
"MDUyMDEyNTE1N1oXDTI0MDUyMDEyNTE1N1owgYsxCzAJBgNVBAYTAlVTMRMwEQYD\r\n"
"VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy\r\n"
"b3NvZnQgQ29ycG9yYXRpb24xFTATBgNVBAsTDE1pY3Jvc29mdCBJVDEeMBwGA1UE\r\n"
"AxMVTWljcm9zb2Z0IElUIFRMUyBDQSAyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A\r\n"
"MIICCgKCAgEAnqoVwRuhY1/mURjFFrsR3AtNm5EKukBJK9zWBgvFd1ksNEJFC06o\r\n"
"yRbwKPMflpW/HtOfzIeBliGk57MwZq18bgASr70sPUWuoD917HUgBfxBYoF8zA7Z\r\n"
"Ie5zAHODFboJL7Fg/apgbQs/GiZZNCi0QkQUWzw0nTUmVSNQ0mz6pCu95Dv1WMsL\r\n"
"GyPGfdN9zD3Q/QEDyJ695QgjRIxYA1DUE+54ti2k6r0ycKFQYkyWwZ25HD1h2kYt\r\n"
"3ovW85vF6y7tjTqUEcLbgKUCB81/955hdLLsbFd6f9o2PkU8xuOc3U+bUedvv6Sb\r\n"
"tvGjBEZeFyH8/CaQhzlsKMH0+OPOFv/bMqcLarPw1V1sOV1bl4W9vi2278niblzI\r\n"
"bEHt7nN888p4KNIwqCcXaGhbtS4tjn3NKI6v1d2XRyxIvCJDjgoZ09zF39Pyoe92\r\n"
"sSRikZh7xns4tQEQ8BCs4o5NBSx8UxEsgyzNSskWGEWqsIjt+7+A1skDDZv6k2o8\r\n"
"VCHNbTLFKS7d72wMI4ErpzVsBIicxaG2ezuMBBuqThxIiJ+G9zfoP9lxim/9rvJA\r\n"
"xbh3nujA1VJfkOYTJIojEAYCxR3QjEoGdapJmBle97AfqEBnwoJsu2wav8h9v+po\r\n"
"DL4h6dRzRUxY1DHypcFlXGoHu/REQgFLq2IN30/AhQLN90Pj9TT2RQECAwEAAaOC\r\n"
"AUIwggE+MB0GA1UdDgQWBBSRnjtEbD1XnEJ3KjTXT9HMSpcs2jAfBgNVHSMEGDAW\r\n"
"gBTlnVkwgkdYzKz6CFQ2hns6tQRN8DASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1Ud\r\n"
"DwEB/wQEAwIBhjAnBgNVHSUEIDAeBggrBgEFBQcDAQYIKwYBBQUHAwIGCCsGAQUF\r\n"
"BwMJMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGln\r\n"
"aWNlcnQuY29tMDoGA1UdHwQzMDEwL6AtoCuGKWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0\r\n"
"LmNvbS9PbW5pcm9vdDIwMjUuY3JsMD0GA1UdIAQ2MDQwMgYEVR0gADAqMCgGCCsG\r\n"
"AQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMA0GCSqGSIb3DQEB\r\n"
"CwUAA4IBAQBsf+pqb89rW8E0rP/cDuB9ixMX4C9OWQ7EA7n0BSllR64ZmuhU9mTV\r\n"
"2L0G4HEiGXvOmt15i99wJ0ho2/dvMxm1ZeufkAfMuEc5fQ9RE5ENgNR2UCuFB2Bt\r\n"
"bVmaKUAWxscN4GpXS4AJv+/HS0VXs5Su19J0DA8Bg+lo8ekCl4dq2G1m1WsCvFBI\r\n"
"oLIjd4neCLlGoxT2jA43lj2JpQ/SMkLkLy9DXj/JHdsqJDR5ogcij4VIX8V+bVD0\r\n"
"NCw7kQa6Ulq9Zo0jDEq1at4zSeH4mV2PMM3LwIXBA2xo5sda1cnUWJo3Pq4uMgcL\r\n"
"e0t+fCut38NMkTl8F0arflspaqUVVUov\r\n"
"-----END CERTIFICATE-----\r\n";

#if IOTHUB_AUTH_METHOD == IOTHUB_AUTH_CLIENT_SIDE_CERT

/*
 * (optional) Client certificate here in PEM format.
 * Set NULL if you don't use.
 * "-----BEGIN CERTIFICATE-----\n"
 * ...
 * "-----END CERTIFICATE-----\n";
 */
const char* SSL_CLIENT_CERT_PEM = "-----BEGIN CERTIFICATE-----\n"
"MIIDXjCCAkagAwIBAgIQcZx5vzDAYo9CdReCOmIZjjANBgkqhkiG9w0BAQsFADAo\n"
"MSYwJAYDVQQDDB1BenVyZSBJb1QgQ0EgVGVzdE9ubHkgUm9vdCBDQTAeFw0yMTAx\n"
"MTAyMDE3NTNaFw0yMTAyMDkyMDI3NTNaMBMxETAPBgNVBAMMCFNUTTMySU9UMIIB\n"
"IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA09/Td8h5eiTvtULrxEiqMi1C\n"
"ZQswilvTlzsMaPOMSq3+YVEnU10zhmUeemSb/+JktlxjZcmYWyhSbhiL2qopJNhN\n"
"sEnn/fAeP0l7hEn+qO3OUm3zklmzue9J70vI5aWxP4Sd2YUn1bZ8inzV7G8xJ1q5\n"
"oVvaddJGtCOwZw4GehjaihViTWfTOu5B7TcTLDYL0m81mDkf8AF6XXGQ/chgxJLq\n"
"GZ0KDhw98aOxy5jon4hkBvTwPD/+FiCoGSYfVDExDtOrc0kLTCsM3npIkch6/EEj\n"
"QFgZi9oaZ4Q78U3VxWAr48H/7DW8jUZHw5+VAVxIdWucdnD8iJjq2FHBxkHaaQID\n"
"AQABo4GYMIGVMA4GA1UdDwEB/wQEAwIFoDATBgNVHREEDDAKgghTVE0zMklPVDAd\n"
"BgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwIBADAf\n"
"BgNVHSMEGDAWgBRe+PC9mPVpt6pDV6Fz9lQSWOY3GDAdBgNVHQ4EFgQUq1DDjZ0s\n"
"jQRE3qr8i7bqE1mponowDQYJKoZIhvcNAQELBQADggEBAK1g9iPCXy1s6wstAETc\n"
"dlguQvkMdyEhF9VMhtZWktmvKZ33rIQCF/7IdtFzrydHsv1POg/x1YVToNYZFi+F\n"
"ELi1OUWWVt9/ERN0aUkxV6JHu5Fi+QsoUNPWI4lGA9h2MnUKWEU1OCHVNvFYEhuH\n"
"rrFacbf1s1zOeTezt1KUBhuioXJfsZ7smKNLQ76PhmNjvLVv+3U+CUh2MIV3m3SR\n"
"1rqQnL8IaoLuJsvaHktWlFSiy/aY23W5Oc8hHwPSGYwXslApX5/9arIGZdg43NDe\n"
"vVgUBTbh1ScnhyHbUxMl+6nR/FNX4Zm6BNsvQIFzfs5upK3LdKoFW28ewyYJtNRl\n"
"VnI=\n"
"-----END CERTIFICATE-----\n";

/*
 * (optional) Client private key here in PEM format.
 * Set NULL if you don't use.
 * "-----BEGIN RSA PRIVATE KEY-----\n"
 * ...
 * "-----END RSA PRIVATE KEY-----\n";
 */
const char* SSL_CLIENT_PRIVATE_KEY_PEM = "-----BEGIN RSA PRIVATE KEY-----\n"
"MIIEowIBAAKCAQEA09/Td8h5eiTvtULrxEiqMi1CZQswilvTlzsMaPOMSq3+YVEn\n"
"U10zhmUeemSb/+JktlxjZcmYWyhSbhiL2qopJNhNsEnn/fAeP0l7hEn+qO3OUm3z\n"
"klmzue9J70vI5aWxP4Sd2YUn1bZ8inzV7G8xJ1q5oVvaddJGtCOwZw4GehjaihVi\n"
"TWfTOu5B7TcTLDYL0m81mDkf8AF6XXGQ/chgxJLqGZ0KDhw98aOxy5jon4hkBvTw\n"
"PD/+FiCoGSYfVDExDtOrc0kLTCsM3npIkch6/EEjQFgZi9oaZ4Q78U3VxWAr48H/\n"
"7DW8jUZHw5+VAVxIdWucdnD8iJjq2FHBxkHaaQIDAQABAoIBAQDBsvA2oy4Dr/8B\n"
"/PNkmHYYt23qyKcQ5tBzgwVeccJBh/524+WK/jsb1BhgFtjTwBsI6T/qD7rdI+jw\n"
"RDqfp09EIwgrcfXJH5vXiguFLszFjdtBWsoCc0WvaAd04RkCck+wXUKeWXDInjQP\n"
"u/8rT6BldTkePsZjTuFa0QH1xUnAlouaYL22LnTRuon88ct65vhYdmDqTGwzpfBs\n"
"xarA2qJ0gHBRiIS92H8v0mZAFLFS34u1H7Wky/KBrb2QxxPhsiKBHjKKfkBKeCyf\n"
"KfgK67OJD/1FGfw2VgDcMYIWYCK+1gBll4KnzUPMhXFHbG+nZqljhSHWLUEPhYkf\n"
"HbMxTdQdAoGBAPeWT2yp6q2R0ICBASc7IY5j3r9S3dLwEiZ+mW7cS6Bqhh2UtBMe\n"
"l57Nb4dmBh3l90kbA2aVIpBQuOZtiEk5PiWMqvLHQTgaidfemCHFvD6XXY4ldjZu\n"
"oIEGffLm2VoTisHtpw9Lq8Dm6bU4yjuJwcYZG8AgVjZKena5fL14ocH3AoGBANsS\n"
"3DCqpRsHf8Owf4e+U6Xz2Cx4ONBC/G6GYsFUgq47BrcfG+CMncvfBHOr/yIuRb6m\n"
"P9hG97qy4cr7kbdSQEpkq4ciqdw5K0iqWX3z1Qn6HaJsNU5wcZ9IdqBxr+7r5qdB\n"
"WA011AJz83bhnRGiiwRpsR+UPyNz9yre09hCkC6fAoGAWFJbpQT8fcydl6ntkmQq\n"
"tVP1O0VBcqVHpEnXTE/z/pbhnx3UG1n3dqQMnD2OAw5tZ7vmO6sJ+HeDblg2nQB5\n"
"pgWHWjIwluYItGRo2utiGuX+bt34TLSsNzrspUEq2lJMVqADz5YMADWfu5E1u4WK\n"
"BbQhTSl798Qb6cyDrkehVMMCgYBn7eud/uazCvy25p2p1UYzvZn5htNVIeJFwOVK\n"
"2H/ijkgiSdTc03jsxhGDmr5ABfm6d35kaU6PONvbgzte39t2L4ocYvp4anq5T2+D\n"
"TFDuGcVDT9h+LOQKb8MvXJ/dVfantF1Ebxv0SfPfmyr7ucP/xPBtjdPiStqgcPPJ\n"
"bdKe+wKBgAxG3ZhkAFViMdaj0iwlEOoN+MhktwU2KPS0FUnEa6eJSMRAAai6DxID\n"
"baGQ/LJQhW2Ewsq99YptlmNdTuYm6dRoAXYIzKNu37XHYFSG7hwgRXOv58ra53gQ\n"
"YxiOyEtFWrI9jN3d7cavf3G2t22yhZcFPTrKiakDmpfT3+bIs++1\n"
"-----END RSA PRIVATE KEY-----\n";

#endif // IOTHUB_AUTH_METHOD == IOTHUB_AUTH_CLIENT_SIDE_CERT

#endif /* __MQTT_SERVER_SETTING_H__ */
